sudo: true
language: java
jdk:
  - openjdk7 # just run openJdk - oraclejdk7
env:
  global:
    - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
    - TRAVIS_PYTHON_VERSION="2.7"
cache:
  directories:
  - $HOME/.m2
install:
  - "travis_retry pip install -q sphinx==1.1.3 --use-mirrors"
  - "travis_wait mvn install -DskipTests=true -f pom-libs.xml -B -V" #download dependencies
  - "travis_wait mvn install -f docs/pom.xml --batch --quiet -Dtycho.mode=maven -Pdocs -B -V" #build documentation using sphinx

script: "travis_wait mvn install --batch --quiet -Pproduct -Psdk -B -V"

notifications:
  email:
    on_success: never
    on_failure: never
  irc:
    channels: "irc.freenode.org#udig"
    on_success: change
    on_failure: always
    template: "%{repository} (%{branch}:%{commit}): %{message} (%{build_url})"
branches:
  only:
    - luna-support
    - master
