# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Maven repository caching
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Load dependencies with pom-libs.xml
      run: mvn -B install --file pom-libs.xml
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          sphinx==4.2.0
    - name: Build docs with sphinx
      run: mvn install -B -f docs/pom.xml -Dtycho.mode=maven -Pdocs
    - name: Run uDig product & sdk build (parallel)
      run: mvn install -B -Pproduct,sdk,test -DskipTests --fail-at-end -T4
    - name: Run uDig tests
      uses: GabrielBB/xvfb-action@v1
      with:
         run: mvn integration-test -B -Ptest --fail-at-end
    - name: provide Windows product for download
      uses: actions/upload-artifact@v2
      with:
        name: udig-product.win32.win32.x86_64
        path: ${{ github.workspace }}/features/org.locationtech.udig-product/target/products/org.locationtech.udig-product/win32/win32/x86_64
    - name: provide Linux product for download
      uses: actions/upload-artifact@v2
      with:
        name: udig-product.linux.gtk.x86_64
        path: ${{ github.workspace }}/features/org.locationtech.udig-product/target/products/org.locationtech.udig-product/linux/gtk/x86_64
    - name: provide MacOSX product for download
      uses: actions/upload-artifact@v2
      with:
        name: udig-product.macosx.cocoa.x86_64
        path: ${{ github.workspace }}/features/org.locationtech.udig-product/target/products/org.locationtech.udig-product/macosx/cocoa/x86_64
    - name: provide User documentation
      uses: actions/upload-artifact@v2
      with:
        name: user-doc
        path: ${{ github.workspace }}/docs/target/user/en/html
